# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(default='inactiv', max_length=40),
        ),
    ]
