# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
