# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0002_auto_20170121_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='task',
            field=models.ForeignKey(default=2, on_delete=models.SET(1), to='DocumentsFlowApp.Task'),
        ),
    ]
