# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0003_auto_20170121_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
