# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.CharField(default='document', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(default='document', max_length=100),
        ),
    ]
