# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0004_auto_20161128_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='assigment',
            name='documentTypes',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='flux',
            name='documents',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='assigment',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='DocumentsFlowApp.Assigment'),
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DocumentsFlowApp.Process'),
        ),
    ]
