# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0005_auto_20170121_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='link',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='task',
            field=models.ForeignKey(default=2, on_delete=models.SET(110), to='DocumentsFlowApp.Task'),
        ),
    ]
