# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0005_auto_20170119_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='superior',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
