# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0005_auto_20161128_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=256)),
                ('flux', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DocumentsFlowApp.Flux')),
            ],
        ),
    ]
