# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0006_group_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='board',
            field=models.IntegerField(default=-1),
        ),
    ]
