# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0006_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('templateValues', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DocumentsFlowApp.Task')),
                ('template', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DocumentsFlowApp.Template')),
            ],
        ),
    ]
