# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0008_document_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 9, 21, 47, 43, 249663)),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.FloatField(default=0.1),
        ),
    ]
