# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0008_assigment_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='step',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(default='activ', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.IntegerField(default=-1),
        ),
    ]
