# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentsFlowApp', '0009_auto_20170109_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 9, 22, 15, 31, 944862)),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
